name: Multi-Stage CI/CD Pipeline

trigger:
  branches:
    include:
      - main
      - develop
  paths:
    exclude:
      - docs/**
      - '*.md'

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  dotnetVersion: '8.0.x'

stages:
  - stage: Build
    displayName: 'Build and Test'
    jobs:
      - job: CompileCode
        displayName: 'Compile Application'
        steps:
          - task: UseDotNet@2
            displayName: 'Setup .NET SDK'
            inputs:
              version: $(dotnetVersion)

          - script: dotnet restore
            displayName: 'Restore dependencies'

          - script: dotnet build --configuration $(buildConfiguration) --no-restore
            displayName: 'Build solution'

      - job: RunTests
        displayName: 'Run Unit Tests'
        dependsOn: CompileCode
        steps:
          - task: UseDotNet@2
            inputs:
              version: $(dotnetVersion)

          - script: dotnet restore
            displayName: 'Restore dependencies'

          - script: dotnet test --configuration $(buildConfiguration) --logger trx
            displayName: 'Execute tests'

  - stage: Deploy
    displayName: 'Deploy to Staging'
    dependsOn: Build
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
    jobs:
      - job: DeployApp
        displayName: 'Deploy Application'
        pool:
          vmImage: 'windows-latest'
        steps:
          - pwsh: Write-Host "Deploying application to staging environment..."
            displayName: 'Deploy to staging'

          - bash: echo "Deployment completed successfully"
            displayName: 'Deployment summary'
