name: Multi-Job Workflow

on: [push, pull_request]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate setup
        run: echo "Setup complete"

  build-backend:
    runs-on: ubuntu-latest
    needs: setup
    env:
      SERVICE: backend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0'
      - run: dotnet build ./src/backend
      - run: dotnet test ./tests/backend

  build-frontend:
    runs-on: ubuntu-latest
    needs: setup
    env:
      SERVICE: frontend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm ci
        working-directory: ./src/frontend
      - run: npm run build
        working-directory: ./src/frontend

  integration-test:
    runs-on: ubuntu-latest
    needs: [build-backend, build-frontend]
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - name: Run integration tests
        run: ./scripts/integration-tests.sh
        shell: bash

  deploy:
    runs-on: ubuntu-latest
    needs: integration-test
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to production
        run: echo "Deploying to production"
        env:
          DEPLOY_ENV: production
