name: Node.js Build Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: node:18

    steps:
      - name: Show Node version
        run: node --version

      - name: Show npm version
        run: npm --version

      - name: List workspace contents
        run: ls -la

      - name: Initialize package.json
        run: npm init -y || echo "package.json already exists"

      - name: Install dependencies
        run: npm install || echo "No dependencies to install"
